### ISSUE TITLE
UX fixes: latest balance is confusing

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/ethcalate-moneyshot#95]
Balances in channel accordion only show the latest nonce. If you spam a bunch of transactions or there are a bunch of non-checkpointed updates, it gets confusing to figure out which updates are actually verified.

We should come up with a better way to handle this.

**Comment by rhlsthrm** [comment]
I think this is okay, because if you spam a bunch of updates the other person can use any of them to close. And since we only let you send money, effectively the latest one you send (or is sent to you) will be the one that is used to close the channel. When you click the button to close channel, you see the latest checkpointed state.

**Comment by LayneHaber** [comment]
Wait okay, so what's the consensus here? I think this should get wrapped in with our discussion re: updating state and checkpointing UX

**Comment by ArjunBhuptani** [comment]
This can get bundled with #119 and pushed to next week, closing
